name: Snyk Demo

on:
  workflow_dispatch:

jobs:
  snyk-scan-nodejs:
    name: Snyk Scan
    uses: ./.github/workflows/snyk.yaml
    secrets: inherit
    with:
      language-tooling: 'nodejs'
      node-version: 'lts/gallium'

  snyk-scan-docker:
    name: Snyk Scan - Docker
    uses: ./.github/workflows/snyk.yaml
    secrets: inherit
    with:
      language-tooling: 'docker'