name: Snyk Demo

on:
  workflow_dispatch:

jobs:
  snyk-scan-nodejs:
    name: Snyk Scan
    uses: ./.github/workflows/snyk-scan-nodejs.yaml
    secrets: inherit
    with:
      node-version: 'lts/gallium'

  # snyk-scan-docker:
  #   name: Snyk Scan - Docker
  #   uses: ./.github/workflows/snyk-scan-nodejs.yaml.yaml
  #   secrets: inherit
  #   with:
  #     language-tooling: 'docker'